/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as AuthenticatedRecrutamentoRouteImport } from './routes/_authenticated/recrutamento'
import { Route as AuthenticatedGestaoRouteImport } from './routes/_authenticated/gestao'
import { Route as AuthenticatedFeriasRouteImport } from './routes/_authenticated/ferias'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedColaboradoresRouteImport } from './routes/_authenticated/colaboradores'
import { Route as AuthenticatedGestaoIndexRouteImport } from './routes/_authenticated/gestao.index'
import { Route as AuthenticatedCandidatosIndexRouteImport } from './routes/_authenticated/candidatos.index'
import { Route as AuthenticatedGestaoAbsenteismoRouteImport } from './routes/_authenticated/gestao.absenteismo'
import { Route as AuthenticatedCandidatosIdRouteImport } from './routes/_authenticated/candidatos.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecrutamentoRoute =
  AuthenticatedRecrutamentoRouteImport.update({
    id: '/recrutamento',
    path: '/recrutamento',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGestaoRoute = AuthenticatedGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeriasRoute = AuthenticatedFeriasRouteImport.update({
  id: '/ferias',
  path: '/ferias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedColaboradoresRoute =
  AuthenticatedColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGestaoIndexRoute =
  AuthenticatedGestaoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGestaoRoute,
  } as any)
const AuthenticatedCandidatosIndexRoute =
  AuthenticatedCandidatosIndexRouteImport.update({
    id: '/candidatos/',
    path: '/candidatos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGestaoAbsenteismoRoute =
  AuthenticatedGestaoAbsenteismoRouteImport.update({
    id: '/absenteismo',
    path: '/absenteismo',
    getParentRoute: () => AuthenticatedGestaoRoute,
  } as any)
const AuthenticatedCandidatosIdRoute =
  AuthenticatedCandidatosIdRouteImport.update({
    id: '/candidatos/$id',
    path: '/candidatos/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/ferias': typeof AuthenticatedFeriasRoute
  '/gestao': typeof AuthenticatedGestaoRouteWithChildren
  '/recrutamento': typeof AuthenticatedRecrutamentoRoute
  '/c/$token': typeof CTokenRoute
  '/candidatos/$id': typeof AuthenticatedCandidatosIdRoute
  '/gestao/absenteismo': typeof AuthenticatedGestaoAbsenteismoRoute
  '/candidatos/': typeof AuthenticatedCandidatosIndexRoute
  '/gestao/': typeof AuthenticatedGestaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/ferias': typeof AuthenticatedFeriasRoute
  '/recrutamento': typeof AuthenticatedRecrutamentoRoute
  '/c/$token': typeof CTokenRoute
  '/candidatos/$id': typeof AuthenticatedCandidatosIdRoute
  '/gestao/absenteismo': typeof AuthenticatedGestaoAbsenteismoRoute
  '/candidatos': typeof AuthenticatedCandidatosIndexRoute
  '/gestao': typeof AuthenticatedGestaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/ferias': typeof AuthenticatedFeriasRoute
  '/_authenticated/gestao': typeof AuthenticatedGestaoRouteWithChildren
  '/_authenticated/recrutamento': typeof AuthenticatedRecrutamentoRoute
  '/c/$token': typeof CTokenRoute
  '/_authenticated/candidatos/$id': typeof AuthenticatedCandidatosIdRoute
  '/_authenticated/gestao/absenteismo': typeof AuthenticatedGestaoAbsenteismoRoute
  '/_authenticated/candidatos/': typeof AuthenticatedCandidatosIndexRoute
  '/_authenticated/gestao/': typeof AuthenticatedGestaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/colaboradores'
    | '/configuracoes'
    | '/dashboard'
    | '/documentos'
    | '/ferias'
    | '/gestao'
    | '/recrutamento'
    | '/c/$token'
    | '/candidatos/$id'
    | '/gestao/absenteismo'
    | '/candidatos/'
    | '/gestao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/colaboradores'
    | '/configuracoes'
    | '/dashboard'
    | '/documentos'
    | '/ferias'
    | '/recrutamento'
    | '/c/$token'
    | '/candidatos/$id'
    | '/gestao/absenteismo'
    | '/candidatos'
    | '/gestao'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/_authenticated/colaboradores'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/ferias'
    | '/_authenticated/gestao'
    | '/_authenticated/recrutamento'
    | '/c/$token'
    | '/_authenticated/candidatos/$id'
    | '/_authenticated/gestao/absenteismo'
    | '/_authenticated/candidatos/'
    | '/_authenticated/gestao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CTokenRoute: typeof CTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recrutamento': {
      id: '/_authenticated/recrutamento'
      path: '/recrutamento'
      fullPath: '/recrutamento'
      preLoaderRoute: typeof AuthenticatedRecrutamentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gestao': {
      id: '/_authenticated/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof AuthenticatedGestaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ferias': {
      id: '/_authenticated/ferias'
      path: '/ferias'
      fullPath: '/ferias'
      preLoaderRoute: typeof AuthenticatedFeriasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/colaboradores': {
      id: '/_authenticated/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof AuthenticatedColaboradoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gestao/': {
      id: '/_authenticated/gestao/'
      path: '/'
      fullPath: '/gestao/'
      preLoaderRoute: typeof AuthenticatedGestaoIndexRouteImport
      parentRoute: typeof AuthenticatedGestaoRoute
    }
    '/_authenticated/candidatos/': {
      id: '/_authenticated/candidatos/'
      path: '/candidatos'
      fullPath: '/candidatos/'
      preLoaderRoute: typeof AuthenticatedCandidatosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gestao/absenteismo': {
      id: '/_authenticated/gestao/absenteismo'
      path: '/absenteismo'
      fullPath: '/gestao/absenteismo'
      preLoaderRoute: typeof AuthenticatedGestaoAbsenteismoRouteImport
      parentRoute: typeof AuthenticatedGestaoRoute
    }
    '/_authenticated/candidatos/$id': {
      id: '/_authenticated/candidatos/$id'
      path: '/candidatos/$id'
      fullPath: '/candidatos/$id'
      preLoaderRoute: typeof AuthenticatedCandidatosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedGestaoRouteChildren {
  AuthenticatedGestaoAbsenteismoRoute: typeof AuthenticatedGestaoAbsenteismoRoute
  AuthenticatedGestaoIndexRoute: typeof AuthenticatedGestaoIndexRoute
}

const AuthenticatedGestaoRouteChildren: AuthenticatedGestaoRouteChildren = {
  AuthenticatedGestaoAbsenteismoRoute: AuthenticatedGestaoAbsenteismoRoute,
  AuthenticatedGestaoIndexRoute: AuthenticatedGestaoIndexRoute,
}

const AuthenticatedGestaoRouteWithChildren =
  AuthenticatedGestaoRoute._addFileChildren(AuthenticatedGestaoRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedColaboradoresRoute: typeof AuthenticatedColaboradoresRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedFeriasRoute: typeof AuthenticatedFeriasRoute
  AuthenticatedGestaoRoute: typeof AuthenticatedGestaoRouteWithChildren
  AuthenticatedRecrutamentoRoute: typeof AuthenticatedRecrutamentoRoute
  AuthenticatedCandidatosIdRoute: typeof AuthenticatedCandidatosIdRoute
  AuthenticatedCandidatosIndexRoute: typeof AuthenticatedCandidatosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedColaboradoresRoute: AuthenticatedColaboradoresRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedFeriasRoute: AuthenticatedFeriasRoute,
  AuthenticatedGestaoRoute: AuthenticatedGestaoRouteWithChildren,
  AuthenticatedRecrutamentoRoute: AuthenticatedRecrutamentoRoute,
  AuthenticatedCandidatosIdRoute: AuthenticatedCandidatosIdRoute,
  AuthenticatedCandidatosIndexRoute: AuthenticatedCandidatosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CTokenRoute: CTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
